/**
 * POST /api/tts/generate  ·  GET /api/tts/generate?text=...
 *
 * Server-side proxy to the ElevenLabs TTS API.
 *
 *   POST accepts JSON: { text, voiceId?, modelId? }
 *   GET  accepts query: ?text=...&voiceId=...&modelId=...
 *
 * Both return:
 *   { status: "completed", audioBase64: string, mimeType: "audio/mpeg", durationSeconds: number }
 *
 * The frontend AudioBriefingPlayer accepts a `data:` URI as its `audio.url`,
 * so the base64 blob is wrapped as `data:audio/mpeg;base64,...` on the
 * client side, or consumed directly via an API response handler.
 *
 * This is the SECONDARY fallback. The PRIMARY path is pre-rendered MP3
 * files in `public/audio/briefings/`, generated by
 * scripts/generate-briefing-audio.ts.
 *
 * Server-only — never marked "use client".
 */

import { NextRequest, NextResponse } from "next/server";

const ELEVENLABS_API_KEY = process.env.ELEVENLABS_API_KEY;
const DEFAULT_VOICE_ID = process.env.ELEVENLABS_VOICE_ID;
const DEFAULT_MODEL = process.env.ELEVENLABS_MODEL ?? "eleven_multilingual_v2";

/* ------------------------------------------------------------------ */
/*  ElevenLabs call                                                  */
/* ------------------------------------------------------------------ */

interface ElevenLabsResponse {
  audioBuffer: Buffer;
  durationSeconds: number;
}

async function callElevenLabs(
  text: string,
  voiceId: string,
  modelId: string,
): Promise<ElevenLabsResponse> {
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}`;

  // ElevenLabs caps at 50 000 chars; clip to stay safely under.
  const trimmed = text.length > 48_000 ? text.slice(0, 48_000) : text;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "xi-api-key": ELEVENLABS_API_KEY ?? "",
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
    },
    body: JSON.stringify({
      text: trimmed,
      model_id: modelId,
      voice_settings: {
        stability: 0.5,
        similarity_boost: 0.75,
        style: 0.0,
        use_speaker_boost: true,
      },
    }),
  });

  if (!response.ok) {
    const errText = await response.text().catch(() => "(no body)");
    throw new Error(`ElevenLabs error ${response.status}: ${errText}`);
  }

  const arrayBuf = await response.arrayBuffer();
  const audioBuffer = Buffer.from(arrayBuf);

  // Duration from header if ElevenLabs provides it; otherwise estimate.
  const durHdr = response.headers.get("x-audio-duration");
  const durationSeconds = durHdr
    ? parseFloat(durHdr)
    : Math.round((trimmed.split(/\s+/).length / 130) * 100) / 100;

  return { audioBuffer, durationSeconds };
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                           */
/* ------------------------------------------------------------------ */

function toDataUri(buffer: Buffer): string {
  const base64 = buffer.toString("base64");
  return `data:audio/mpeg;base64,${base64}`;
}

/* ------------------------------------------------------------------ */
/*  Route handlers                                                    */
/* ------------------------------------------------------------------ */

export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}));

    const text = typeof body.text === "string" ? body.text.trim() : "";
    if (!text) {
      return NextResponse.json(
        { error: "Field 'text' (string) is required." },
        { status: 400 },
      );
    }

    const voiceId = body.voiceId ?? DEFAULT_VOICE_ID;
    const modelId = body.modelId ?? DEFAULT_MODEL;

    if (!voiceId || !ELEVENLABS_API_KEY) {
      return NextResponse.json(
        { error: "ELEVENLABS_API_KEY and ELEVENLABS_VOICE_ID env vars (or request body) are required." },
        { status: 500 },
      );
    }

    const { audioBuffer, durationSeconds } = await callElevenLabs(text, voiceId, modelId);

    return NextResponse.json({
      status: "completed",
      audioUrl: toDataUri(audioBuffer),
      durationSeconds,
      mimeType: "audio/mpeg",
    });
  } catch (err) {
    console.error("[TTS API] POST error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Generation failed" },
      { status: 500 },
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const text = searchParams.get("text")?.trim();
    if (!text) {
      return NextResponse.json(
        { error: "Query parameter 'text' is required." },
        { status: 400 },
      );
    }

    const voiceId = searchParams.get("voiceId") ?? DEFAULT_VOICE_ID;
    const modelId = searchParams.get("modelId") ?? DEFAULT_MODEL;

    if (!voiceId || !ELEVENLABS_API_KEY) {
      return NextResponse.json(
        { error: "ELEVENLABS_API_KEY and ELEVENLABS_VOICE_ID must be set." },
        { status: 500 },
      );
    }

    const { audioBuffer, durationSeconds } = await callElevenLabs(text, voiceId, modelId);

    return NextResponse.json({
      status: "completed",
      audioUrl: toDataUri(audioBuffer),
      durationSeconds,
      mimeType: "audio/mpeg",
    });
  } catch (err) {
    console.error("[TTS API] GET error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Generation failed" },
      { status: 500 },
    );
  }
}